source 'https://rubygems.org'
#ruby '1.9.3'
gem 'octokit', '~> 3.3'
gem 'faraday', '~> 0.9'
gem 'httpclient', '~> 2.4'
gem 'nokogiri', '~> 1.6'
gem 'git', '~> 1.2'
gem 'parallel', '~> 1.2'
gem 'puma', '~> 2.9'
gem 'sinatra', '~> 1.4'
gem 'sinatra-contrib', '~> 1.4'
gem 'i18n', '~> 0.7'
